services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio_crud
    ports:
      - "3306:3306"